cat << EOF > pup.rb
# This file was generated by release.sh
require 'formula'
class Pup < Formula
  homepage 'https://github.com/prateekgogia/importing-go-modules'
  version '0.4.0'
  url 'https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_darwin_386.zip'
  sha256 '$( sha256sum dist/${DARWIN_AMD64}  | awk '{ print $1 }' | xargs printf )'
  def install
    bin.install 'pup'
  end
end
EOF